Repository Elonsoft/esfront, pull requests merged in 2022-04, with the labels that each got.

#66 feat: add missing hues to info, success and warning palettes
  commitlint.config.js
  src/theming/palettes/dark/info.ts
  src/theming/palettes/dark/success.ts
  src/theming/palettes/dark/warning.ts
  src/theming/palettes/light/info.ts
  src/theming/palettes/light/success.ts
  src/theming/palettes/light/warning.ts
Labels: enhancement

#68 fix(Pagination): add missing types
  src/overrides.d.ts
Labels: bug, enhancement

#65 feat(Switch): add new component
  src/components/Switch/Switch.api.stories.mdx
  src/components/Switch/Switch.classes.ts
  src/components/Switch/Switch.spec.tsx
  src/components/Switch/Switch.stories.mdx
  src/components/Switch/Switch.tsx
  src/components/Switch/Switch.types.ts
  src/components/Switch/index.ts
  src/components/index.ts
  src/hooks/index.ts
  src/hooks/useControlled/index.ts
  src/hooks/useControlled/useControlled.api.stories.mdx
  src/hooks/useControlled/useControlled.stories.mdx
  src/hooks/useControlled/useControlled.ts
  src/overrides.d.ts
Labels: enhancement

#69 docs: add icons documentation
  .storybook/preview.js
  src/documentation/components/IconsDemo.tsx
  src/documentation/icons.stories.mdx
Labels: documentation

#70 fix(Dialog): add missing types
  src/overrides.d.ts
Labels: bug, enhancement

#71 feat: change alpha, surface and background hues
  src/theming/palettes/common/black.ts
  src/theming/palettes/common/white.ts
  src/theming/palettes/dark/blue.ts
  src/theming/palettes/dark/brown.ts
  src/theming/palettes/dark/common.ts
  src/theming/palettes/dark/error.ts
  src/theming/palettes/dark/green.ts
  src/theming/palettes/dark/grey.ts
  src/theming/palettes/dark/info.ts
  src/theming/palettes/dark/marine.ts
  src/theming/palettes/dark/monoA.ts
  src/theming/palettes/dark/monoB.ts
  src/theming/palettes/dark/orange.ts
  src/theming/palettes/dark/pink.ts
  src/theming/palettes/dark/primary.ts
  src/theming/palettes/dark/purple.ts
  src/theming/palettes/dark/red.ts
  src/theming/palettes/dark/secondary.ts
  src/theming/palettes/dark/sky.ts
  src/theming/palettes/dark/success.ts
  src/theming/palettes/dark/surface.ts
  src/theming/palettes/dark/teal.ts
  src/theming/palettes/dark/violet.ts
  src/theming/palettes/dark/warning.ts
  src/theming/palettes/dark/yellow.ts
  src/theming/palettes/light/blue.ts
  src/theming/palettes/light/brown.ts
  src/theming/palettes/light/common.ts
  src/theming/palettes/light/error.ts
  src/theming/palettes/light/green.ts
  src/theming/palettes/light/grey.ts
  src/theming/palettes/light/info.ts
  src/theming/palettes/light/marine.ts
  src/theming/palettes/light/monoA.ts
  src/theming/palettes/light/monoB.ts
  src/theming/palettes/light/orange.ts
  src/theming/palettes/light/pink.ts
  src/theming/palettes/light/primary.ts
  src/theming/palettes/light/purple.ts
  src/theming/palettes/light/red.ts
  src/theming/palettes/light/secondary.ts
  src/theming/palettes/light/sky.ts
  src/theming/palettes/light/success.ts
  src/theming/palettes/light/teal.ts
  src/theming/palettes/light/violet.ts
  src/theming/palettes/light/warning.ts
  src/theming/palettes/light/yellow.ts
Labels: enhancement

#73 fix(AudioPlayer): close menu on current time slider click
  src/components/AudioPlayer/AudioPlayer.tsx
Labels: bug

#72 feat(Alert): add new component
  src/components/Alert/Alert.api.stories.mdx
  src/components/Alert/Alert.classes.ts
  src/components/Alert/Alert.stories.mdx
  src/components/Alert/Alert.tsx
  src/components/Alert/Alert.types.ts
  src/components/Alert/AlertActions/AlertActions.api.stories.mdx
  src/components/Alert/AlertActions/AlertActions.classes.ts
  src/components/Alert/AlertActions/AlertActions.tsx
  src/components/Alert/AlertActions/AlertActions.types.ts
  src/components/Alert/AlertActions/index.ts
  src/components/Alert/AlertClose/AlertClose.api.stories.mdx
  src/components/Alert/AlertClose/AlertClose.classes.ts
  src/components/Alert/AlertClose/AlertClose.tsx
  src/components/Alert/AlertClose/AlertClose.types.ts
  src/components/Alert/AlertClose/index.ts
  src/components/Alert/AlertTitle/AlertTitle.api.stories.mdx
  src/components/Alert/AlertTitle/AlertTitle.classes.ts
  src/components/Alert/AlertTitle/AlertTitle.tsx
  src/components/Alert/AlertTitle/AlertTitle.types.ts
  src/components/Alert/AlertTitle/index.ts
  src/components/Alert/index.ts
  src/components/index.ts
  src/components/locale/index.ts
  src/icons/IconAlert.tsx
  src/icons/IconCheckCircle.tsx
  src/icons/IconCloseMd.tsx
  src/icons/IconCloseOctagon.tsx
  src/icons/IconInfo.tsx
  src/icons/index.ts
  src/overrides.d.ts
Labels: enhancement

#76 docs: use relative assets paths
  src/components/Swiper/Swiper.stories.tsx
Labels: documentation

#77 fix(SwiperButton): increase styles specificity
  src/components/Swiper/Swiper.stories.tsx
  src/components/Swiper/SwiperButton/SwiperButton.tsx
Labels: bug

#75 docs: use self-hosted fonts with corrected vertical metrics
  .storybook/assets/fonts/Roboto-Bold.ttf
  .storybook/assets/fonts/Roboto-Light.ttf
  .storybook/assets/fonts/Roboto-Medium.ttf
  .storybook/assets/fonts/Roboto-Regular.ttf
  .storybook/preview-head.html
Labels: documentation

#79 feat(useForceUpdate): add new hook
  src/hooks/index.ts
  src/hooks/useForceUpdate/index.ts
  src/hooks/useForceUpdate/useForceUpdate.api.stories.mdx
  src/hooks/useForceUpdate/useForceUpdate.stories.mdx
  src/hooks/useForceUpdate/useForceUpdate.stories.tsx
  src/hooks/useForceUpdate/useForceUpdate.ts
Labels: enhancement

#80 feat(useUpdateEffect): add new hook
  src/hooks/index.ts
  src/hooks/useUpdateEffect/index.ts
  src/hooks/useUpdateEffect/useUpdateEffect.api.stories.mdx
  src/hooks/useUpdateEffect/useUpdateEffect.stories.mdx
  src/hooks/useUpdateEffect/useUpdateEffect.stories.tsx
  src/hooks/useUpdateEffect/useUpdateEffect.ts
Labels: enhancement

#81 feat(useDebounce): add new hook
  src/hooks/index.ts
  src/hooks/useDebounce/index.ts
  src/hooks/useDebounce/useDebounce.api.stories.mdx
  src/hooks/useDebounce/useDebounce.stories.mdx
  src/hooks/useDebounce/useDebounce.stories.tsx
  src/hooks/useDebounce/useDebounce.ts
  src/hooks/useForceUpdate/useForceUpdate.stories.tsx
Labels: enhancement

#82 feat(useClipboard): add new hook
  src/hooks/index.ts
  src/hooks/useClipboard/index.ts
  src/hooks/useClipboard/useClipboard.api.stories.mdx
  src/hooks/useClipboard/useClipboard.stories.mdx
  src/hooks/useClipboard/useClipboard.stories.tsx
  src/hooks/useClipboard/useClipboard.ts
Labels: enhancement
