Repository Elonsoft/esfront, pull requests merged in 2022-12, with the labels that each got.

#119 feat(Button)!: change button colors and sizes
  src/components/Alert/Alert.stories.mdx
  src/components/Alert/AlertClose/AlertClose.tsx
  src/components/AvatarGroup/AvatarGroup.stories.mdx
  src/components/Dialog/Dialog.stories.tsx
  src/components/Dialog/DialogArrow/DialogArrow.tsx
  src/components/Dialog/DialogClose/DialogClose.tsx
  src/components/Pagination/PaginationPages/PaginationPages.tsx
  src/components/Pagination/PaginationRange/PaginationRange.tsx
  src/overrides.d.ts
  src/theming/ThemeProvider/createTheme.ts
  src/theming/components/button/button.stories.mdx
  src/theming/components/button/button.ts
  src/theming/components/icon-button/icon-button.stories.mdx
  src/theming/components/icon-button/icon-button.ts
  src/theming/components/menu/menu.stories.tsx
  src/theming/mixins/button.ts
  src/theming/palettes/common/black.ts
  src/theming/palettes/common/white.ts
  src/theming/palettes/dark/monoB.ts
  src/theming/palettes/light/monoB.ts
  src/theming/typography/typography.ts
Labels: enhancement

#121 fix(Table): add resize observer for the scrolling ancestor
  src/hooks/useSticky/useSticky.ts
Labels: bug

#127 docs: add changelog page
  .storybook/main.js
  .storybook/preview.js
  src/documentation/CHANGELOG.stories.mdx
Labels: documentation
