Repository Elonsoft/esfront, pull requests merged in 2023-08, with the labels that each got.

#133 feat(SidebarItem): change tooltip styles
  src/components/Sidebar/SidebarItem/SidebarItem.classes.ts
  src/components/Sidebar/SidebarItem/SidebarItem.tsx
  src/components/Sidenav/SidenavItem/SidenavItem.tsx
Labels: enhancement

#162 fix(EmptyState): change heading and subheading types to ReactNode
  src/components/EmptyState/EmptyState.types.ts
Labels: enhancement

#159 fix(Swiper): add smooth snap after mouse drag
  src/components/Swiper/Swiper.tsx
Labels: bug

#160 feat(TableText): add tooltip for truncated text
  src/components/Table/Table.stories.tsx
  src/components/Table/TableRow/TableRow.tsx
  src/components/Table/TableText/TableText.classes.ts
  src/components/Table/TableText/TableText.tsx
  src/components/Table/TableText/TableText.types.ts
Labels: enhancement

#149 feat(useTableSelection): add new hook
  src/components/Table/Table.stories.tsx
  src/components/Table/index.ts
  src/components/Table/useTableSelection.ts
Labels: enhancement

#164 fix(Table)!: change sticky implementation
  src/components/Table/Table.stories.mdx
  src/components/Table/Table.stories.tsx
  src/components/Table/Table.tsx
  src/components/Table/TableBody/TableBody.context.ts
  src/components/Table/TableBody/TableBody.tsx
  src/components/Table/TableBody/index.ts
  src/components/Table/TableFoot/TableFoot.classes.ts
  src/components/Table/TableFoot/TableFoot.tsx
  src/components/Table/TableFoot/TableFoot.types.ts
  src/components/Table/TableHead/TableHead.classes.ts
  src/components/Table/TableHead/TableHead.context.ts
  src/components/Table/TableHead/TableHead.tsx
  src/components/Table/TableHead/TableHead.types.ts
  src/components/Table/TableHead/index.ts
  src/components/Table/TableScrollable/TableScrollable.api.stories.mdx
  src/components/Table/TableScrollable/TableScrollable.classes.ts
  src/components/Table/TableScrollable/TableScrollable.tsx
  src/components/Table/TableScrollable/TableScrollable.types.ts
  src/components/Table/TableScrollable/index.ts
  src/components/Table/index.ts
  src/components/Table/useTableResize.ts
  src/hooks/useScrollSync/useScrollSync.ts
  src/overrides.d.ts
Labels: bug, enhancement
