Repository Elonsoft/esfront, pull requests merged in 2023-11, with the labels that each got.

#191 fix(TableScrollbar): increase inner block height
  src/components/Table/TableScrollbar/TableScrollbar.tsx
Labels: bug

#189 feat(PageHGroup): add new component
  cspell.json
  src/components/Breadcrumbs/Breadcrumbs.stories.tsx
  src/components/PageHGroup/PageHGroup.api.stories.mdx
  src/components/PageHGroup/PageHGroup.classes.ts
  src/components/PageHGroup/PageHGroup.stories.mdx
  src/components/PageHGroup/PageHGroup.stories.tsx
  src/components/PageHGroup/PageHGroup.tsx
  src/components/PageHGroup/PageHGroup.types.ts
  src/components/PageHGroup/PageHGroupActions/PageHGroupActions.api.stories.mdx
  src/components/PageHGroup/PageHGroupActions/PageHGroupActions.classes.ts
  src/components/PageHGroup/PageHGroupActions/PageHGroupActions.tsx
  src/components/PageHGroup/PageHGroupActions/PageHGroupActions.types.ts
  src/components/PageHGroup/PageHGroupActions/index.ts
  src/components/PageHGroup/PageHGroupBreadcrumbs/PageHGroupBreadcrumbs.api.stories.mdx
  src/components/PageHGroup/PageHGroupBreadcrumbs/PageHGroupBreadcrumbs.classes.ts
  src/components/PageHGroup/PageHGroupBreadcrumbs/PageHGroupBreadcrumbs.tsx
  src/components/PageHGroup/PageHGroupBreadcrumbs/PageHGroupBreadcrumbs.types.ts
  src/components/PageHGroup/PageHGroupBreadcrumbs/index.ts
  src/components/PageHGroup/PageHGroupHeading/PageHGroupHeading.api.stories.mdx
  src/components/PageHGroup/PageHGroupHeading/PageHGroupHeading.classes.ts
  src/components/PageHGroup/PageHGroupHeading/PageHGroupHeading.tsx
  src/components/PageHGroup/PageHGroupHeading/PageHGroupHeading.types.ts
  src/components/PageHGroup/PageHGroupHeading/index.ts
  src/components/PageHGroup/PageHGroupMain/PageHGroupMain.api.stories.mdx
  src/components/PageHGroup/PageHGroupMain/PageHGroupMain.classes.ts
  src/components/PageHGroup/PageHGroupMain/PageHGroupMain.tsx
  src/components/PageHGroup/PageHGroupMain/PageHGroupMain.types.ts
  src/components/PageHGroup/PageHGroupMain/index.ts
  src/components/PageHGroup/PageHGroupStatus/PageHGroupStatus.api.stories.mdx
  src/components/PageHGroup/PageHGroupStatus/PageHGroupStatus.classes.ts
  src/components/PageHGroup/PageHGroupStatus/PageHGroupStatus.tsx
  src/components/PageHGroup/PageHGroupStatus/PageHGroupStatus.types.ts
  src/components/PageHGroup/PageHGroupStatus/index.ts
  src/components/PageHGroup/index.ts
  src/components/index.ts
  src/overrides.d.ts
Labels: enhancement

#190 feat(AppBar): add new component
  src/components/AppBar/AppBar.api.stories.mdx
  src/components/AppBar/AppBar.classes.ts
  src/components/AppBar/AppBar.stories.mdx
  src/components/AppBar/AppBar.stories.tsx
  src/components/AppBar/AppBar.tsx
  src/components/AppBar/AppBar.types.ts
  src/components/AppBar/index.ts
  src/components/index.ts
  src/hooks/useIntersectionObserver/useIntersectionObserver.ts
  src/overrides.d.ts
Labels: enhancement

#187 feat(TabBar): add new component
  src/components/TabBar/TabBar.api.stories.mdx
  src/components/TabBar/TabBar.classes.ts
  src/components/TabBar/TabBar.stories.mdx
  src/components/TabBar/TabBar.stories.tsx
  src/components/TabBar/TabBar.tsx
  src/components/TabBar/TabBar.types.ts
  src/components/TabBar/TabBarItem/TabBarItem.api.stories.mdx
  src/components/TabBar/TabBarItem/TabBarItem.classes.ts
  src/components/TabBar/TabBarItem/TabBarItem.tsx
  src/components/TabBar/TabBarItem/TabBarItem.types.ts
  src/components/TabBar/TabBarItem/index.ts
  src/components/TabBar/index.ts
  src/components/index.ts
  src/overrides.d.ts
Labels: enhancement

#194 refactor(Link): replace alpha function with color-mix
  src/components/Link/Link.tsx
Labels: enhancement

#195 fix(AutocompleteField): safely pass callbacks from InputProps to Autocomplete component
  src/components/AutocompleteField/AutocompleteField.tsx
Labels: bug, enhancement
