Repository Elonsoft/esfront, pull requests merged in 2023-06, with the labels that each got.

#152 fix(Kbd): change root element name
  cspell.json
  src/components/Kbd/Kbd.tsx
Labels: bug

#154 fix(Breadcrumbs): add child validity check
  src/components/Breadcrumbs/Breadcrumbs.tsx
Labels: bug

#150 feat(PasswordField): add new component
  src/components/PasswordField/PasswordField.api.stories.mdx
  src/components/PasswordField/PasswordField.classes.ts
  src/components/PasswordField/PasswordField.stories.mdx
  src/components/PasswordField/PasswordField.tsx
  src/components/PasswordField/PasswordField.types.ts
  src/components/PasswordField/index.ts
  src/components/index.ts
  src/components/locale/index.ts
  src/overrides.d.ts
Labels: enhancement

#132 feat(Sidebar): add secondary color
  src/components/Sidebar/Sidebar.context.ts
  src/components/Sidebar/Sidebar.stories.mdx
  src/components/Sidebar/Sidebar.tsx
  src/components/Sidebar/Sidebar.types.ts
  src/components/Sidebar/SidebarDivider/SidebarDivider.tsx
  src/components/Sidebar/SidebarItem/SidebarItem.tsx
  src/components/Sidebar/SidebarToggle/SidebarToggle.tsx
  src/components/Sidenav/Sidenav.stories.mdx
  src/components/Sidenav/Sidenav.stories.tsx
  src/components/Sidenav/SidenavItem/SidenavItem.tsx
Labels: documentation, enhancement
