Repository Elonsoft/esfront, pull requests merged in 2024-02, with the labels that each got.

#221 feat(Calendar): add new component
  src/components/Calendar/Calendar.api.stories.mdx
  src/components/Calendar/Calendar.classes.ts
  src/components/Calendar/Calendar.stories.tsx
  src/components/Calendar/Calendar.tsx
  src/components/Calendar/Calendar.types.ts
  src/components/Calendar/CalendarButton/CalendarButton.api.stories.mdx
  src/components/Calendar/CalendarButton/CalendarButton.classes.ts
  src/components/Calendar/CalendarButton/CalendarButton.tsx
  src/components/Calendar/CalendarButton/CalendarButton.types.ts
  src/components/Calendar/CalendarButton/index.ts
  src/components/Calendar/CalendarHead/CalendarHead.api.stories.mdx
  src/components/Calendar/CalendarHead/CalendarHead.classes.ts
  src/components/Calendar/CalendarHead/CalendarHead.tsx
  src/components/Calendar/CalendarHead/CalendarHead.types.ts
  src/components/Calendar/CalendarHead/index.ts
  src/components/Calendar/index.ts
  src/components/Calendar/useCalendar.ts
  src/components/index.ts
  src/components/locale/index.ts
  src/overrides.d.ts
  src/theming/components/tooltip/tooltip.ts
Labels: enhancement

#223 fix(CalendarButton): reduce button height
  src/components/Calendar/CalendarButton/CalendarButton.tsx
Labels: bug, enhancement

#222 fix(Calendar): pass ownerState to styled components
  src/components/Calendar/Calendar.tsx
  src/components/Calendar/CalendarButton/CalendarButton.tsx
  src/components/Calendar/CalendarHead/CalendarHead.tsx
Labels: bug

#226 feat(FileIconBadge): increase border radius
  src/components/FileIcon/FileIconBadge/FileIconBadge.tsx
Labels: enhancement

#224 fix(Sidebar): correct typos in styled components names
  src/components/Sidebar/SidebarItem/SidebarItem.tsx
  src/components/Sidebar/SidebarToggle/SidebarToggle.tsx
Labels: bug

#228 fix(CalendarButton): replace of S syntax with subsequent-sibling combinator
  src/components/Calendar/CalendarButton/CalendarButton.tsx
Labels: bug

#225 feat(AutocompleteMenu): add new component
  src/components/Autocomplete/Autocomplete.classes.ts
  src/components/Autocomplete/Autocomplete.tsx
  src/components/Autocomplete/Autocomplete.types.ts
  src/components/Autocomplete/AutocompleteFooter/AutocompleteFooter.api.stories.mdx
  src/components/Autocomplete/AutocompleteFooter/AutocompleteFooter.classes.ts
  src/components/Autocomplete/AutocompleteFooter/AutocompleteFooter.tsx
  src/components/Autocomplete/AutocompleteFooter/index.ts
  src/components/Autocomplete/AutocompleteHeader/AutocompleteHeader.api.stories.mdx
  src/components/Autocomplete/AutocompleteHeader/AutocompleteHeader.classes.ts
  src/components/Autocomplete/AutocompleteHeader/AutocompleteHeader.tsx
  src/components/Autocomplete/AutocompleteHeader/index.ts
  src/components/Autocomplete/index.ts
  src/components/AutocompleteField/AutocompleteField.stories.tsx
  src/components/AutocompleteMenu/AutocompleteMenu.api.stories.mdx
  src/components/AutocompleteMenu/AutocompleteMenu.classes.ts
  src/components/AutocompleteMenu/AutocompleteMenu.tsx
  src/components/AutocompleteMenu/AutocompleteMenu.types.ts
  src/components/AutocompleteMenu/AutocompleteMenuFooter/AutocompleteMenuFooter.api.stories.mdx
  src/components/AutocompleteMenu/AutocompleteMenuFooter/AutocompleteMenuFooter.classes.ts
  src/components/AutocompleteMenu/AutocompleteMenuFooter/AutocompleteMenuFooter.tsx
  src/components/AutocompleteMenu/AutocompleteMenuFooter/AutocompleteMenuFooter.types.ts
  src/components/AutocompleteMenu/AutocompleteMenuFooter/index.ts
  src/components/AutocompleteMenu/AutocompleteMenuHeader/AutocompleteMenuHeader.api.stories.mdx
  src/components/AutocompleteMenu/AutocompleteMenuHeader/AutocompleteMenuHeader.classes.ts
  src/components/AutocompleteMenu/AutocompleteMenuHeader/AutocompleteMenuHeader.tsx
  src/components/AutocompleteMenu/AutocompleteMenuHeader/AutocompleteMenuHeader.types.ts
  src/components/AutocompleteMenu/AutocompleteMenuHeader/index.ts
  src/components/AutocompleteMenu/index.ts
  src/components/index.ts
  src/components/locale/index.ts
  src/hooks/index.ts
  src/hooks/useScrollLock/index.ts
  src/hooks/useScrollLock/useScrollLock.tsx
  src/overrides.d.ts
Labels: enhancement

#231 fix(scrollbars): disable scrollbar-width for webkit browsers
  cspell.json
  src/documentation/components/ScrollbarsDemo.tsx
  src/theming/scrollbars/scrollbars.ts
Labels: bug

#200 feat(scrollbars): add color variants
  src/components/AutocompleteMenu/AutocompleteMenu.tsx
  src/components/SFS/SFSFilters/SFSFilters.tsx
  src/components/SFS/SFSSorting/SFSSorting.tsx
  src/components/Sidebar/SidebarItem/SidebarItem.tsx
  src/components/Sidebar/SidebarScrollable/SidebarScrollable.tsx
  src/components/Table/TableScrollbar/TableScrollbar.tsx
  src/documentation/components/ScrollbarsDemo.tsx
  src/overrides.d.ts
  src/theming/scrollbars/scrollbars.ts
Labels: enhancement

#232 fix(GallerySwiperImage): add utility class to image element
  src/components/Gallery/GallerySwiperImage/GallerySwiperImage.classes.ts
  src/components/Gallery/GallerySwiperImage/GallerySwiperImage.tsx
Labels: bug

#233 fix(Swiper): update buttons and pagination states on children count change
  src/components/Swiper/Swiper.tsx
Labels: bug

#234 build: add @use-gesture/react to peerDependencies
  package.json
Labels: enhancement
