Repository Elonsoft/esfront, pull requests merged in 2024-06, with the labels that each got.

#311 build: upgrade @mui/material to v5.15.19
  package-lock.json
  packages/react/package.json
Labels: bug, enhancement

#313 feat(Gallery): change root component
  packages/react/src/components/Gallery/Gallery.tsx
Labels: enhancement

#312 feat(useValueGate): add new hook
  packages/react/src/hooks/index.ts
  packages/react/src/hooks/useValueGate/index.ts
  packages/react/src/hooks/useValueGate/useValueGate.api.mdx
  packages/react/src/hooks/useValueGate/useValueGate.stories.tsx
  packages/react/src/hooks/useValueGate/useValueGate.ts
Labels: enhancement

#318 docs: revert to react-docgen-typescript
  cspell.json
  packages/react/.storybook/main.js
  packages/react/src/components/Button/Button.stories.tsx
Labels: documentation

#307 feat: update typography
  packages/react/src/theming/typography/typography.ts
Labels: enhancement

#309 feat(PasswordField): add tooltip
  packages/react/src/components/PasswordField/PasswordField.tsx
  packages/react/src/components/PasswordField/PasswordField.types.ts
  packages/react/src/components/locale/index.ts
Labels: enhancement

#294 feat(Breadcrumb): add itemContent prop
  cspell.json
  packages/react/src/components/Breadcrumbs/Breadcrumb/Breadcrumb.tsx
  packages/react/src/components/Breadcrumbs/Breadcrumb/Breadcrumb.types.ts
  packages/react/src/components/Breadcrumbs/Breadcrumbs.stories.tsx
Labels: enhancement

#287 fix(SidebarItem): force behaviour click on touch devices
  packages/react/src/components/Sidebar/SidebarItem/SidebarItem.tsx
Labels: bug

#230 feat(Badge): add new component
  packages/react/src/components/Badge/Badge.api.mdx
  packages/react/src/components/Badge/Badge.classes.ts
  packages/react/src/components/Badge/Badge.stories.tsx
  packages/react/src/components/Badge/Badge.tsx
  packages/react/src/components/Badge/Badge.types.ts
  packages/react/src/components/Badge/index.ts
  packages/react/src/components/index.ts
  packages/react/src/overrides.d.ts
Labels: enhancement

#238 feat(RibbonBadge): add new component
  packages/react/src/components/RibbonBadge/RibbonBadge.classes.ts
  packages/react/src/components/RibbonBadge/RibbonBadge.stories.tsx
  packages/react/src/components/RibbonBadge/RibbonBadge.tsx
  packages/react/src/components/RibbonBadge/RibbonBadge.types.ts
  packages/react/src/components/RibbonBadge/index.ts
  packages/react/src/components/index.ts
  packages/react/src/overrides.d.ts
Labels: enhancement

#249 feat(Checkbox): add new component
  packages/react/src/components/Checkbox/Checkbox.api.mdx
  packages/react/src/components/Checkbox/Checkbox.classes.ts
  packages/react/src/components/Checkbox/Checkbox.stories.tsx
  packages/react/src/components/Checkbox/Checkbox.tsx
  packages/react/src/components/Checkbox/Checkbox.types.ts
  packages/react/src/components/Checkbox/CheckboxIcon/CheckboxIcon.api.mdx
  packages/react/src/components/Checkbox/CheckboxIcon/CheckboxIcon.classes.ts
  packages/react/src/components/Checkbox/CheckboxIcon/CheckboxIcon.tsx
  packages/react/src/components/Checkbox/CheckboxIcon/CheckboxIcon.types.ts
  packages/react/src/components/Checkbox/CheckboxIcon/index.ts
  packages/react/src/components/Checkbox/icons/IconCheckLarge.tsx
  packages/react/src/components/Checkbox/icons/IconCheckMedium.tsx
  packages/react/src/components/Checkbox/icons/IconCheckSmall.tsx
  packages/react/src/components/Checkbox/icons/IconIndeterminateLarge.tsx
  packages/react/src/components/Checkbox/icons/IconIndeterminateMedium.tsx
  packages/react/src/components/Checkbox/icons/IconIndeterminateSmall.tsx
  packages/react/src/components/Checkbox/icons/index.ts
  packages/react/src/components/Checkbox/index.ts
  packages/react/src/components/SwitchBase/SwitchBase.api.mdx
  packages/react/src/components/SwitchBase/SwitchBase.classes.ts
  packages/react/src/components/SwitchBase/SwitchBase.tsx
  packages/react/src/components/SwitchBase/SwitchBase.types.ts
  packages/react/src/components/SwitchBase/index.ts
  packages/react/src/components/index.ts
  packages/react/src/overrides.d.ts
  packages/react/src/theming/components/checkbox/checkbox.tsx
Labels: enhancement

#328 style: enable no-restricted-properties rule
  packages/configs/eslint-config/index.js
  packages/react/.storybook/components/TableBase.tsx
  packages/react/src/components/Checkbox/Checkbox.tsx
  packages/react/src/components/Checkbox/CheckboxIcon/CheckboxIcon.tsx
  packages/react/src/components/Radio/Radio.tsx
  packages/react/src/components/Radio/RadioIcon/RadioIcon.tsx
  packages/react/src/components/RibbonBadge/RibbonBadge.tsx
  packages/react/src/components/Spinner/SpinnerFadingDoubleRing/SpinnerFadingDoubleRing.tsx
  packages/react/src/components/Spinner/SpinnerFadingRing/SpinnerFadingRing.tsx
  packages/react/src/components/Switch/Switch.tsx
Labels: enhancement

#320 feat(ButtonBase): change focus state
  packages/react/src/components/Breadcrumbs/Breadcrumb/Breadcrumb.tsx
  packages/react/src/components/Button/Button.stories.tsx
  packages/react/src/components/Button/Button.tsx
  packages/react/src/components/Button/Button.types.ts
  packages/react/src/components/ButtonBase/ButtonBase.tsx
  packages/react/src/components/Calendar/CalendarButton/CalendarButton.tsx
  packages/react/src/components/Checkbox/Checkbox.tsx
  packages/react/src/components/Dropzone/Dropzone.tsx
  packages/react/src/components/Gallery/GalleryActionsButton/GalleryActionsButton.tsx
  packages/react/src/components/Gallery/GallerySwiper/GallerySwiper.tsx
  packages/react/src/components/Gallery/GalleryThumbnails/GalleryThumbnails.tsx
  packages/react/src/components/Gallery/GalleryThumbnailsItem/GalleryThumbnailsItem.tsx
  packages/react/src/components/Pagination/PaginationPages/PaginationPages.tsx
  packages/react/src/components/Radio/Radio.tsx
  packages/react/src/components/Sidebar/SidebarItem/SidebarItem.tsx
  packages/react/src/components/Sidebar/SidebarToggle/SidebarToggle.tsx
  packages/react/src/components/Switch/Switch.tsx
  packages/react/src/components/SwitchBase/SwitchBase.tsx
Labels: enhancement
