Repository Elonsoft/esfront, pull requests merged in 2024-11, with the labels that each got.

#364 fix(PaginationPages): add unique key prop
  packages/react/src/components/Pagination/PaginationPages/PaginationPages.tsx
Labels: bug

#363 fix(Swiper): change loop edges detection
  packages/react/src/components/Swiper/Swiper.tsx
Labels: bug

#213 feat(Chip): add new component
  packages/react/src/components/Chip/Chip.api.mdx
  packages/react/src/components/Chip/Chip.classes.ts
  packages/react/src/components/Chip/Chip.stories.tsx
  packages/react/src/components/Chip/Chip.tsx
  packages/react/src/components/Chip/Chip.types.ts
  packages/react/src/components/Chip/index.ts
  packages/react/src/components/index.ts
  packages/react/src/icons/IconChipsClose.tsx
  packages/react/src/icons/IconCloseLineW350.tsx
  packages/react/src/icons/index.ts
  packages/react/src/overrides.d.ts
Labels: enhancement

#369 build: upgrade storybook to v8.4.5
  .github/workflows/pull_request.yml
  package-lock.json
  package.json
  packages/react/.storybook/components/Description.tsx
  packages/react/.storybook/components/TableBase.tsx
  packages/react/.storybook/components/TableFunction.tsx
  packages/react/.storybook/components/TableInterface.tsx
  packages/react/package.json
  packages/react/src/components/AutocompleteField/AutocompleteField.stories.tsx
  packages/react/src/components/Chip/Chip.stories.tsx
  packages/react/src/components/ListItem/ListItem.types.ts
  packages/react/src/components/MenuItem/MenuItem.types.ts
  packages/react/tsconfig.json
Labels: documentation, enhancement
