Repository Elonsoft/esfront, pull requests merged in 2024-10, with the labels that each got.

#355 fix(Badge): add missing export type
  packages/react/src/components/Badge/index.ts
Labels: bug

#343 feat(RibbonBadge): add focus state
  packages/react/src/components/RibbonBadge/RibbonBadge.tsx
Labels: enhancement

#359 feat(BottomSheet): add drag dom scope check
  packages/react/src/components/BottomSheet/BottomSheet.tsx
Labels: enhancement

#358 fix(Checkbox): disable hover state for touchscreen devices
  packages/react/src/components/Checkbox/Checkbox.tsx
  packages/react/src/components/Radio/Radio.tsx
Labels: bug

#360 fix(MenuItem): add forward ref
  packages/react/src/components/AutocompleteMenu/AutocompleteMenu.tsx
  packages/react/src/components/MenuItem/MenuItem.tsx
Labels: bug, enhancement

#322 style: upgrade eslint to v9
  .dependency-cruiser.cjs
  .eslintignore
  .eslintrc.json
  .prettierrc.js
  commitlint.config.cjs
  eslint.config.js
  package-lock.json
  package.json
  packages/configs/cspell-config/index.json
  packages/configs/eslint-config/README.md
  packages/configs/eslint-config/index.js
  packages/configs/eslint-config/package.json
  packages/react/.storybook/main.js
  packages/react/import-icons.js
  packages/react/src/components/Badge/Badge.types.ts
  packages/react/src/components/BottomSheet/BottomSheet.tsx
  packages/react/src/components/Breadcrumbs/Breadcrumb/Breadcrumb.types.ts
  packages/react/src/components/Breadcrumbs/Breadcrumbs.tsx
  packages/react/src/components/Button/Button.stories.tsx
  packages/react/src/components/Button/Button.types.ts
  packages/react/src/components/ButtonBase/ButtonBase.types.ts
  packages/react/src/components/Link/Link.types.ts
  packages/react/src/components/ListItem/ListItem.types.ts
  packages/react/src/components/LoadingButton/LoadingButton.types.ts
  packages/react/src/components/MadeBy/MadeBy.types.ts
  packages/react/src/components/Menu/Menu.stories.tsx
  packages/react/src/components/MenuItem/MenuItem.types.ts
  packages/react/src/components/Pagination/PaginationPages/PaginationPages.tsx
  packages/react/src/components/RadioGroup/useRadioGroup.ts
  packages/react/src/components/RibbonBadge/RibbonBadge.types.ts
  packages/react/src/components/SFS/SFSButton/SFSButton.types.ts
  packages/react/src/components/Sidebar/SidebarItem/SidebarItem.types.ts
  packages/react/src/components/Sidenav/SidenavItem/SidenavItem.types.ts
  packages/react/src/components/Spinner/SpinnerDashRing/SpinnerDashRing.types.ts
  packages/react/src/components/Spinner/SpinnerFadingBars/SpinnerFadingBars.types.ts
  packages/react/src/components/Spinner/SpinnerFadingDots/SpinnerFadingDots.types.ts
  packages/react/src/components/Spinner/SpinnerFadingDoubleRing/SpinnerFadingDoubleRing.types.ts
  packages/react/src/components/Spinner/SpinnerFadingRing/SpinnerFadingRing.types.ts
  packages/react/src/components/Spinner/SpinnerRing/SpinnerRing.types.ts
  packages/react/src/components/SwitchBase/SwitchBase.types.ts
  packages/react/src/components/TabBar/TabBarItem/TabBarItem.types.ts
  packages/react/src/components/Table/TableRow/TableRow.types.ts
  packages/react/src/hooks/useCallbackThrottle/useCallbackThrottle.api.mdx
  packages/react/src/hooks/usePagination/usePagination.ts
  packages/react/src/hooks/useThrottle/useThrottle.api.mdx
  packages/react/src/hooks/useValueThrottle/useValueThrottle.api.mdx
  packages/react/src/overrides.d.ts
  packages/react/src/theming/components/menu/menu.stories.tsx
  packages/react/src/theming/components/tooltip/tooltip.stories.tsx
Labels: enhancement
